services:
  sshitmaids:
    build: ./container
    image: sshitmaids:latest
    container_name: sshitmaids
    environment:
      - SSHITMAIDS_DEST=${SSHITMAIDS_DEST:-"git@github.com:22"}
      - GENERATE_CLIENT_CONFIG=${SSHITMAIDS_GENERATE_CLIENT_CONFIG:-"false"}
      - CLIENT_DEST=${SSHITMAIDS_CLIENT_DEST:-"git@sshitmaids:22"}
    ports:
      - "${SSHITMAIDS_PUBLIC_PORT:-2222}:22"
    volumes:
      - ./volumes/sshitmaids:/root/sshitmaids
      - ./volumes/ssh-client:/root/ssh-client
    restart: unless-stopped